import { Amplify } from 'aws-amplify';
import { fetchAuthSession } from 'aws-amplify/auth';
import React, { createContext, useContext, useEffect, useState } from 'react';

// Configure Amplify
// In real app, these come from environment variables or a config file generated by Terraform
const amplifyConfig = {
    Auth: {
        Cognito: {
            userPoolId: import.meta.env.VITE_USER_POOL_ID || 'eu-west-2_example',
            userPoolClientId: import.meta.env.VITE_USER_POOL_CLIENT_ID || 'exampleclientid',
        }
    }
};

Amplify.configure(amplifyConfig);

interface AuthContextType {
    isAuthenticated: boolean;
    isLoading: boolean;
    signOut: () => void;
}

const AuthContext = createContext<AuthContextType>({ isAuthenticated: false, isLoading: true, signOut: () => { } });

export const useAuth = () => useContext(AuthContext);

export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [isAuthenticated, setIsAuthenticated] = useState(false);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        checkAuth();
    }, []);

    const checkAuth = async () => {
        try {
            const session = await fetchAuthSession();
            setIsAuthenticated(!!session.tokens);
        } catch (e) {
            setIsAuthenticated(false);
        } finally {
            setIsLoading(false);
        }
    };

    // Amplify handles sign out state internally usually, but we can wrap it
    const signOut = async () => {
        // Logic handled by components calling Amplify signOut
        setIsAuthenticated(false);
    };

    return (
        <AuthContext.Provider value={{ isAuthenticated, isLoading, signOut }}>
            {children}
        </AuthContext.Provider>
    );
};
